#!/bin/bash 

date
export PS4='+ $SECONDS + '
set -xue

#-----------------------------------------------------------------------
export USHaqm=${EXECaqm:-${HOMEaqm}/ush}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}

export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

. $USHaqm/aqm_nco_config.sh

export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

export CDATE=${PDY}${cyc}

. $USHaqm/job_preamble.sh


cycle_iso=${PDY:04}-${PDY:4:2}-${PDY:6:2}T${cyc}
uw chgres_cube provisioned_rundir \
  --cycle $cycle_iso \
  --config ${USHaqm}/config.yaml \
  --key-path make_ics

#-----------------------------------------------------------------------
# Call the ex-script for this J-job and pass to it the necessary variables.
#-----------------------------------------------------------------------
#
${HOMEaqm}/scripts/exaqm_make_ics.sh
export err=$?; err_chk
#
#======================================================================
msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg "${msg}"

if [ "${KEEPDATA}" != "YES" ]; then
   rm -rf ${DATA}
fi

date
