
task_run_post:
  upp:
    files_to_copy:
      postxconfig-NT.txt: "{{ workflow.PARMdir }}/upp/postxconfig-NT-AQM.txt"
    namelist:
      update_values:
        nampgb:
          aqf_on: true
  output_file_labels:
    - cmaq
